# Generated by Django 5.0.7 on 2024-10-24 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_roles_usuario_groups_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('domicilio', 'Domicilio'), ('paquete', 'Paquete')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_personalizado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_anuncio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=10)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento')),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo': 'paquete'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_personalizado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_anuncio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=10)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento')),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo': 'domicilio'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('apellido_visitante', models.CharField(max_length=100)),
                ('fecha_visita', models.DateTimeField()),
                ('es_frecuente', models.BooleanField(default=False)),
                ('fecha_expiracion_frecuente', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')], default='pendiente', max_length=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('mensaje_qr', models.CharField(blank=True, max_length=255, unique=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento')),
            ],
        ),
    ]
