# Generated by Django 5.0.7 on 2024-11-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_proveedor_paquete_domicilio_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='mensaje_qr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
