# Generated by Django 5.0.7 on 2024-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_visita_mensaje_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='mensaje_qr',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='visita',
            name='notificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
