# Generated by Django 5.0.7 on 2024-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_visita_mensaje_qr_remove_visita_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
