# Generated by Django 5.0.7 on 2024-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='notificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete',
            name='notificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('recogido', 'Recogido')], default='pendiente', max_length=10),
        ),
    ]
