# Generated by Django 5.0.7 on 2025-04-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_domicilio_notificacion_paquete_notificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='roles',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
