# Generated by Django 5.0.7 on 2025-04-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_roles_nombre_roles_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='name',
            new_name='nombre',
        ),
    ]
